[package]
name = "test_debug"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
codelet-common = { path = "../common" }
